#!/usr/bin/env node
/* =============================================================
   TheRacingData — tools/build-web.mjs

   Reconstructed. planner.css referenced this file but it was not
   in the repo, so the scoping step it describes could not run.

   Each tool's CSS is authored unscoped, which keeps it readable
   and lets the standalone page work on its own. Embedding that
   CSS in the site shell would leak: `button { ... }` would restyle
   the marketing pages. This emits a scoped copy where every
   selector is prefixed with the tool's root id, so the same
   stylesheet can be dropped into the shell without leaking.

       css/planner.css  ->  css/planner.scoped.css

   Rules already beginning with the root id are left alone (the
   current files are hand-scoped), which makes this idempotent and
   safe to run over either style of source.

   Usage:  node tools/build-web.mjs [--check]
           --check exits non-zero if any output is stale.
   ============================================================= */

import { readFile, writeFile, readdir, access } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TOOLS_DIR = join(ROOT, '_tools');

/* Tool id -> the element id its markup wraps everything in. */
const SCOPES = {
  'loom-planner':   '#trd-loom-planner',
  'report-builder': '#trd-report-builder',
  'fuel-stint':     '#trd-fuel-stint',
  'load-budget':    '#trd-load-budget',
  'run-plan':       '#trd-run-plan',
  'event-pack':     '#trd-event-pack',
};

/* At-rules whose bodies contain nested rules that still need scoping.
   @font-face, @keyframes and @property bodies are declarations, not
   rules, and must be passed through untouched. */
const NESTED_AT = /^@(media|supports|container|layer)\b/;

function scopeSelector(sel, scope) {
  return sel
    .split(',')
    .map(s => s.trim())
    .filter(Boolean)
    .map(s => {
      if (s.startsWith(scope)) return s;             // already scoped
      if (s === ':root') return scope;               // custom props live on the root
      if (/^(html|body)\b/.test(s)) return s;        // page-level, intentionally global
      if (s.startsWith('@')) return s;
      return `${scope} ${s}`;
    })
    .join(', ');
}

/* A small state machine rather than a regex: CSS nests, and comments
   and strings can both contain braces. */
function scopeCss(css, scope) {
  let out = '';
  let buf = '';
  const stack = [];

  for (let i = 0; i < css.length; i++) {
    const c = css[i];

    if (c === '/' && css[i + 1] === '*') {
      const end = css.indexOf('*/', i + 2);
      const stop = end === -1 ? css.length : end + 2;
      buf += css.slice(i, stop);
      i = stop - 1;
      continue;
    }

    if (c === '{') {
      const prelude = buf.trim();
      buf = '';
      const inNestedAt = stack.some(s => s.nested);
      if (prelude.startsWith('@')) {
        stack.push({ nested: NESTED_AT.test(prelude), at: true });
        out += `${prelude} {`;
      } else {
        const passthrough = stack.length > 0 && !inNestedAt;
        stack.push({ nested: false, at: false });
        out += `${passthrough ? prelude : scopeSelector(prelude, scope)} {`;
      }
      continue;
    }

    if (c === '}') {
      out += buf + '}';
      buf = '';
      stack.pop();
      continue;
    }

    buf += c;
  }
  return out + buf;
}

async function exists(p) {
  try { await access(p); return true; } catch { return false; }
}

const check = process.argv.includes('--check');
let stale = 0, written = 0;

for (const [tool, scope] of Object.entries(SCOPES)) {
  const cssDir = join(TOOLS_DIR, tool, 'css');
  if (!(await exists(cssDir))) {
    console.log(`  skip    ${tool} (no css/)`);
    continue;
  }
  const files = (await readdir(cssDir))
    .filter(f => f.endsWith('.css'))
    .filter(f => !f.endsWith('.scoped.css'))
    // standalone.css is deliberately page-level; scoping it would
    // defeat its only job.
    .filter(f => f !== 'standalone.css');

  for (const file of files) {
    const src = await readFile(join(cssDir, file), 'utf8');
    const outName = file.replace(/\.css$/, '.scoped.css');
    const outPath = join(cssDir, outName);
    const banner =
      `/* GENERATED by tools/build-web.mjs from ${file} — do not edit.\n` +
      `   Every rule scoped under ${scope} for embedding in the site shell. */\n`;
    const next = banner + scopeCss(src, scope);

    const prev = (await exists(outPath)) ? await readFile(outPath, 'utf8') : null;
    if (prev === next) { console.log(`  ok      ${tool}/${outName}`); continue; }

    if (check) { console.error(`  STALE   ${tool}/${outName}`); stale++; continue; }
    await writeFile(outPath, next, 'utf8');
    written++;
    console.log(`  scoped  ${tool}/${file} -> ${outName}`);
  }
}

if (check && stale) {
  console.error(`\n${stale} scoped stylesheet(s) out of date. Run: node tools/build-web.mjs`);
  process.exit(1);
}
console.log(`\nbuild-web: ${written} file(s) written`);
